app = "8wyw74t7yv-alt"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

# 1 GB RAM va 1 CPU sozlashi
[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
